name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false  # Set to false for debugging
          load: true   # Load the image locally
          tags: |
            ghcr.io/mohamedelashri/vscode-container:${{ github.event.inputs.tag }}
            ghcr.io/mohamedelashri/vscode-container:latest
          build-args: |
            USER=vscode
            USER_ID=1000
            GROUP_ID=1000
            WORKDIR=workspace

      - name: Debug - Display Docker image details
        run: |
          docker images
          docker history ghcr.io/mohamedelashri/vscode-container:${{ github.event.inputs.tag }}

      - name: Debug - Run container and check installed packages
        run: |
          docker run --rm ghcr.io/mohamedelashri/vscode-container:${{ github.event.inputs.tag }} apt list --installed

      - name: Push Docker image
        if: success()
        run: |
          docker push ghcr.io/mohamedelashri/vscode-container:${{ github.event.inputs.tag }}
          docker push ghcr.io/mohamedelashri/vscode-container:latest