name: Build and push Docker image
on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image with version tag
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          melashri/vscode-server:${{ github.ref_name }}
          melashri/vscode-server:latest
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        build-args: |
          USER=vscode
          USER_ID=1000
          GROUP_ID=1000
    - name: Debug
      if: failure()
      run: |
        docker build --no-cache -t debug-image .
        docker run --rm debug-image id
        docker run --rm debug-image cat /etc/passwd
        docker run --rm debug-image cat /etc/group
