name: Build and push Docker image

on:
  push:
    tags:
      - 'v*.*'  #  Trigger when a version tag is pushed (e.g., v1.0.0)
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image with version tag
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          melashri/vscode-server:${{ github.ref_name }}  # Tag with the version (e.g., v1.0.0)
          melashri/vscode-server:latest  # Also tag this version as 'latest'
