name: Build and push Docker image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fetch latest VSCode release
        id: fetch_vscode
        uses: actions/github-script@v6
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: 'microsoft',
              repo: 'vscode'
            });
            core.setOutput('version', latest.data.tag_name);

      - name: Determine version to build
        id: set_version
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.fetch_vscode.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Check for existing GitHub release
        id: check_release
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: '${{ steps.set_version.outputs.version }}'
              });
              core.setOutput('exists', 'true');
            } catch (error) {
              core.setOutput('exists', error.status === 404 ? 'false' : 'error');
            }

      - name: Create GitHub release for VSCode ${{ steps.set_version.outputs.version }}
        if: steps.check_release.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_version.outputs.version }}
          release_name: VSCode ${{ steps.set_version.outputs.version }}
          body: Automated release for VSCode version ${{ steps.set_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Check Docker Hub for existing image
        id: check_docker
        run: |
          if docker manifest inspect melashri/vscode-server:${{ steps.set_version.outputs.version }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip build if image already exists
        if: steps.check_docker.outputs.exists == 'true'
        run: |
          echo " Image melashri/vscode-server:${{ steps.set_version.outputs.version }} already exists on Docker Hub. Nothing to do."

      - name: Build and push Docker image
        if: steps.check_docker.outputs.exists == 'false'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            melashri/vscode-server:${{ steps.set_version.outputs.version }}
            melashri/vscode-server:latest
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            USER=vscode
            USER_ID=1000
            GROUP_ID=1000

      - name: Debug (on failure)
        if: failure()
        run: |
          docker build --no-cache -t debug-image .
          docker run --rm debug-image id
          docker run --rm debug-image cat /etc/passwd
          docker run --rm debug-image cat /etc/group
